/* eslint-disable no-restricted-syntax */
import { writeFileSync } from 'fs';
import { join } from 'path';
import config from '../config';
import { CategoryWithIcons } from '../types';
import { prefixWithAutoGeneratedMessage } from '../utils';

const { templates, outputDirectoryPath, indexFilename, messages } = config;

function generateIndex(categoryWithIcons: CategoryWithIcons): void {
    const categories = Object.entries(categoryWithIcons);
    let categoryContent = '';

    for (const [category, icons] of categories) {
        categoryContent += templates.createExport(category);

        let content = '';

        for (const [name] of Object.entries(icons)) {
            content += templates.createExport(name);
        }

        const categoryIndexFilepath = join(
            outputDirectoryPath,
            category,
            indexFilename,
        );

        writeFileSync(
            categoryIndexFilepath,
            prefixWithAutoGeneratedMessage(content),
        );
    }

    const iconsIndexFilepath = join(outputDirectoryPath, indexFilename);

    writeFileSync(
        iconsIndexFilepath,
        prefixWithAutoGeneratedMessage(categoryContent),
    );

    // eslint-disable-next-line no-console
    console.log(messages.generatedIndices);
}

export default generateIndex;
