/* eslint-disable no-restricted-syntax */
import { extname } from 'path';
import config from './config';

const { sourceFileIconSizes, messages } = config;

export function capitalizeFirstLetter(input: string): string {
    return input.charAt(0).toUpperCase() + input.slice(1);
}

export function prefixWithAutoGeneratedMessage(input: string): string {
    return `
        ${messages.generatedFileWarning}

        ${input}
    `;
}

export function getIconSize(name: string): string | undefined {
    const extension = extname(name);
    const fileName = name.replace(extension, '');

    for (const size of sourceFileIconSizes) {
        if (fileName.endsWith(capitalizeFirstLetter(size))) {
            return size;
        }
    }

    return undefined;
}

export function getIconName(name: string): string {
    const extension = extname(name);
    const fileName = name.replace(extension, '');

    let iconName = fileName;

    for (const size of sourceFileIconSizes) {
        iconName = iconName.replace(capitalizeFirstLetter(size), '');
    }

    return iconName;
}
