export const DATA_TABLE_CLASS_PREFIX = 'DataTable';

export const DATA_TABLE_EXPANDABLE_SECTION_OFFSET_LEFT_BASE = 13;
export const DATA_TABLE_EXPANDABLE_SECTION_OFFSET_LEFT_ROW_SELECTION = 12;
export const DATA_TABLE_EMPTY_DATA = [];
export const DATA_TABLE_EMPTY_COLUMNS = [];
export const TABLE_SORTING_DIRECTION_ASC = 'asc';
export const TABLE_SORTING_DIRECTION_DESC = 'desc';
export const TABLE_CHECKBOX_CELL_WIDTH = 48;
