---
kind: pipeline
type: kubernetes
name: build

tolerations:
    - effect: NoSchedule
      key: app
      operator: Exists
node_selector:
    app: drone

service_account_name: 'drone-logistics-staging'

trigger:
    event:
        - pull_request

steps:
    - name: build
      image: node:14
      environment:
        GITHUB_TOKEN:
          from_secret: CICD_PREV_DEPS_TOKEN
      commands:
          - ./script/build-preview.sh

    - name: upload files to s3
      image: 940776968316.dkr.ecr.eu-west-1.amazonaws.com/drone/s3:latest
      settings:
          bucket: production-eu-armor
          assume_role: 'arn:aws:iam::487596255802:role/k8s-staging-eu-drone'
          region: 'eu-west-1'
          source: ./packages/react/dev/.out
          target: /${DRONE_PULL_REQUEST}
