import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { render } from 'ejs';
import { CategoryWithIllustrations } from '../types';
import config from '../config';
import { prefixWithAutoGeneratedMessage } from '../utils';

const { templates, storyDirectoryPath, storyFilename, messages } = config;

function generateStories(
    categoryWithIllustrations: CategoryWithIllustrations,
): void {
    const categories = Object.keys(categoryWithIllustrations);

    const content = render(templates.story, {
        categories: categories.map((category) => ({
            name: category,
            illustrations: Object.keys(categoryWithIllustrations[category]),
        })),
    });

    mkdirSync(storyDirectoryPath);

    const storyPath = join(storyDirectoryPath, storyFilename);

    writeFileSync(storyPath, prefixWithAutoGeneratedMessage(content));

    // eslint-disable-next-line no-console
    console.log(messages.generatedStories);
}

export default generateStories;
