/* eslint-disable no-restricted-syntax */
import { writeFileSync } from 'fs';
import { join } from 'path';
import config from '../config';
import { CategoryWithIllustrations } from '../types';
import { prefixWithAutoGeneratedMessage } from '../utils';

const { templates, outputDirectoryPath, indexFilename, messages } = config;

function generateIndex(
    categoryWithIllustrations: CategoryWithIllustrations,
): void {
    const categories = Object.entries(categoryWithIllustrations);
    let categoryContent = '';

    for (const [category, illustrations] of categories) {
        categoryContent += templates.createExport(category);

        let content = '';

        for (const [name] of Object.entries(illustrations)) {
            content += templates.createExport(name);
        }

        const categoryIndexFilepath = join(
            outputDirectoryPath,
            category,
            indexFilename,
        );

        writeFileSync(
            categoryIndexFilepath,
            prefixWithAutoGeneratedMessage(content),
        );
    }

    const indexFilepath = join(outputDirectoryPath, indexFilename);

    writeFileSync(
        indexFilepath,
        prefixWithAutoGeneratedMessage(categoryContent),
    );

    // eslint-disable-next-line no-console
    console.log(messages.generatedIndices);
}

export default generateIndex;
