/*
 * Package armor-system is used to be part of the armor package once.
 * Re-exporting some stuff for backward compatibility.
 */

export type {
    UnpackedType,
    ScalarType,
    ScaleType,
    MutuallyExclusive,
} from '@deliveryhero/armor-system';

export {
    makeTheme,
    makeDefaultTheme,

    colorGrey90,
    colorGrey80,
    colorGrey70,
    colorGrey60,
    colorGrey50,
    colorGrey40,
    colorGrey30,
    colorGrey20,
    colorGrey10,
    colorGrey05,
    colorGrey01,
    colorGrey00,
    colorBlue90,
    colorBlue80,
    colorBlue70,
    colorBlue60,
    colorBlue50,
    colorBlue40,
    colorBlue30,
    colorBlue20,
    colorBlue10,
    colorBlue05,
    colorTurquoise90,
    colorTurquoise80,
    colorTurquoise70,
    colorTurquoise60,
    colorTurquoise50,
    colorTurquoise40,
    colorTurquoise30,
    colorTurquoise20,
    colorTurquoise10,
    colorTurquoise05,
    colorYellow90,
    colorYellow80,
    colorYellow70,
    colorYellow60,
    colorYellow50,
    colorYellow40,
    colorYellow30,
    colorYellow20,
    colorYellow10,
    colorYellow05,
    colorGreen90,
    colorGreen80,
    colorGreen70,
    colorGreen60,
    colorGreen50,
    colorGreen40,
    colorGreen30,
    colorGreen20,
    colorGreen10,
    colorGreen05,
    colorRed90,
    colorRed80,
    colorRed70,
    colorRed60,
    colorRed50,
    colorRed40,
    colorRed30,
    colorRed20,
    colorRed10,
    colorRed05,
    colorPurple50,
    colorPurple20,

    borderRadius01,
    borderRadius02,
    borderRadius04,
    borderRadiusPill,

    boxShadowSmall,
    boxShadowMedium,
    boxShadowLarge,

    durationNormal,

    fontFamilyRoboto,

    fontSize01,
    fontSize02,
    fontSize03,
    fontSize04,
    fontSize05,

    fontWeightRegular,
    fontWeightMedium,
    fontWeightBold,

    letterSpacingNone,
    letterSpacingSmall,
    letterSpacingMedium,
    letterSpacingLarge,

    lineHeight01,
    lineHeight02,
    lineHeight03,
    lineHeight04,
    lineHeight05,

    componentSpacing01,
    componentSpacing02,
    componentSpacing03,
    componentSpacing04,
    componentSpacing05,
    componentSpacing06,
    componentSpacing07,
    componentSpacing08,
    componentSpacing09,

    layoutSpacing01,
    layoutSpacing02,
    layoutSpacing03,
    layoutSpacing04,
    layoutSpacing05,

    zIndexTableHeader,
    zIndexModal,
    zIndexSearchSuggestionsList,

    color,
    spacing,
    typography,
    pixelToRem,
    borderRadius,
    propsBlocker,

} from '@deliveryhero/armor-system';
