name: CD.REACT

on:
  push:
    branches:
      - master
    paths:
      - "web/packages/react/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install common
        working-directory: ./web
        run: yarn install
      - name: Install
        working-directory: ./web/packages/react
        run: yarn install
        env:
          GITHUB_TOKEN: foo
      - name: Install peers
        working-directory: ./web/packages/react
        run: yarn run install-peers
        env:
          GITHUB_TOKEN: foo
      - name: Build
        working-directory: ./web/packages/react
        run: yarn run build
      - name: Publish
        working-directory: ./web/packages/react
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: foo
