name: CD

on:
    push:
        branches:
            - master
            - beta
        paths:
            - 'packages/**'

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install common
              run: yarn install
            - name: Install (react-icons)
              working-directory: ./packages/react-icons
              run: yarn install
              env:
                  GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}
            - name: Install peers (react-icons)
              working-directory: ./packages/react-icons
              run: yarn run install-peers
              env:
                  GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}
            - name: Build (react-icons)
              working-directory: ./packages/react-icons
              run: yarn run build
              env:
                  GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}
            - name: Install (react)
              working-directory: ./packages/react
              run: yarn install
              env:
                  GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}
            - name: Install peers (react)
              working-directory: ./packages/react
              run: yarn run install-peers
              env:
                  GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}
            - name: Build (react)
              working-directory: ./packages/react
              run: yarn run build
              env:
                  GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}
            - name: Publish
              run: yarn multi-semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}
