name: CD

on:
    push:
        branches:
            - master
            - beta
        paths:
            - 'packages/**'

jobs:
    publish:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}

        steps:
            - uses: actions/checkout@v2
            - name: Install (common)
              run: yarn
            - name: Install peers (common)
              run: yarn install-peers

            - name: Build (system)
              working-directory: ./packages/system
              run: yarn run build

            - name: Build (icons)
              working-directory: ./packages/icons
              run: yarn run build

            - name: Build (core)
              working-directory: ./packages/core
              run: yarn run build

            - name: Build (brands)
              working-directory: ./packages/brands
              run: yarn run build

            - name: Build (illustrations)
              working-directory: ./packages/illustrations
              run: yarn run build

            - name: Build (vendors)
              working-directory: ./packages/vendors
              run: yarn run build

            - name: Build (props-parser)
              working-directory: ./packages/props-parser
              run: yarn run build

            - name: Build (motion)
              working-directory: ./packages/motion
              run: yarn run build

            - name: Remove comments
              run: ./script/remove-comments.js

            - name: Publish
              run: yarn multi-semantic-release | tee ~/.release-output.txt

            - name: Documentation re-deployment
              run: |
                  curl --request POST \
                  --header 'Authorization: token ${{ secrets.CICD_TOKEN }}' \
                  --url https://api.github.com/repos/deliveryhero/armor-docs/actions/workflows/cd.yml/dispatches \
                  --data '{"ref":"master"}'

            - name: Text panic message
              if: failure()
              run: |
                  curl --request POST \
                  --header 'Content-type: application/json' \
                  --url https://hooks.slack.com/services/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 \
                  --data '{"channel" : "armor-devs", "text": "🚨🚨🚨 OMG. The Armor Release pipeline just failed! 🚨🚨🚨", "attachments": [{"text": ":fire:", "footer": "<https://github.com/deliveryhero/armor/actions|Check out right away!>", "mrkdwn_in": ["text"]}]}'
