name: CI.BRANDS

on:
    pull_request:
        branches:
            - dev
            - master
        paths:
            - 'packages/brands/**'

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}

        steps:
            - uses: actions/checkout@v2
            - name: Install (common)
              run: yarn
            - name: Install peers (common)
              run: yarn install-peers

            - name: Build (system)
              working-directory: ./packages/system
              run: yarn build:cjs

            - name: Build (icons)
              working-directory: ./packages/icons
              run: yarn build:cjs

            - name: Build (core)
              working-directory: ./packages/core
              run: yarn build:cjs

            - name: Lint
              working-directory: ./packages/brands
              run: yarn run lint
            - name: Test
              working-directory: ./packages/brands
              run: yarn run test
            - name: Test visual install
              working-directory: ./packages/brands/visual
              run: yarn install
            - name: Test visual
              working-directory: ./packages/brands
              run: yarn test:visual:cicd
            - name: Build
              working-directory: ./packages/brands
              run: yarn run build
