name: CI.CORE

on:
    pull_request:
        branches:
            - dev
            - master
        paths:
            - 'packages/core/**'
            - 'packages/system/**'
env:
    CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
jobs:
    test:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}

        steps:
            - uses: actions/checkout@v2
            - name: Install (common)
              run: yarn
            - name: Install peers (common)
              run: yarn install-peers

            - name: Build (system)
              working-directory: ./packages/system
              run: yarn build:cjs

            - name: Build (icons)
              working-directory: ./packages/icons
              run: yarn build:cjs

            - name: Lint
              working-directory: ./packages/core
              run: yarn run lint

            - name: Test and coverage
              working-directory: ./packages/core
              run: yarn run test --coverage

            - name: Codacy Coverage Reporter
              working-directory: ./packages/core
              run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./src/coverage/lcov.info

            - name: Test integration install
              working-directory: ./packages/core/integration
              run: yarn install

            - name: Test integration
              working-directory: ./packages/core
              run: yarn test:integration:cicd

            - name: Test visual install
              working-directory: ./packages/core/visual
              run: yarn install

            - name: Test visual
              working-directory: ./packages/core
              run: yarn test:visual:cicd

            - name: Build
              working-directory: ./packages/core
              run: yarn run build
