name: CI.CORE

on:
    pull_request:
        branches:
            - dev
            - master
        paths:
            - 'packages/core/**'
            - 'packages/system/**'
jobs:
    test:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}

        steps:
            - uses: actions/checkout@v2

            - name: Install (common)
              run: yarn

            - name: Build (system)
              working-directory: ./packages/system
              run: yarn build:cjs

            - name: Build (icons)
              working-directory: ./packages/icons
              run: yarn build:cjs

            - name: Build (motion)
              working-directory: ./packages/motion
              run: yarn build:cjs

            - name: Lint
              working-directory: ./packages/core
              run: yarn run lint

            - name: Test
              working-directory: ./packages/core
              run: yarn run test

            - name: Test integration install
              working-directory: ./packages/core/integration
              run: yarn install

            - name: Test integration
              working-directory: ./packages/core
              run: yarn test:integration:cicd

            - name: Test visual install
              working-directory: ./packages/core/visual
              run: yarn install

            - name: Test visual
              working-directory: ./packages/core
              run: yarn test:visual:cicd

            - name: Build
              working-directory: ./packages/core
              run: yarn run build
