name: CI.PROPS-PARSER

on:
    pull_request:
        branches:
            - dev
            - master
        paths:
            - 'packages/props-parser/**'

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: './packages/props-parser'

        steps:
            - uses: actions/checkout@v2
            - name: Install
              run: yarn install
              env:
                  GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}
            - name: Lint
              run: yarn lint
              env:
                  GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}
            - name: Test
              run: yarn test
              env:
                  GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}
            - name: Build
              run: yarn run build
              env:
                  GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}
