name: CI.PROPS-PARSER

on:
    pull_request:
        branches:
            - dev
            - master
        paths:
            - 'packages/props-parser/**'

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: './packages/props-parser'

        steps:
            - uses: actions/checkout@v2
            - name: Install (common)
              run: yarn
            - name: Install peers (common)
              run: yarn install-peers

            - name: Lint
              run: yarn lint
            - name: Test
              run: yarn test
            - name: Build
              run: yarn run build
