name: CI.REACT

on:
  pull_request:
    branches:
      - dev
      - master
    paths:
      - "web/packages/react/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install common
        working-directory: ./web
        run: yarn install
      - name: Install
        working-directory: ./web/packages/react
        run: yarn install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install peers
        working-directory: ./web/packages/react
        run: yarn run install-peers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        working-directory: ./web/packages/react
        run: yarn run lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        working-directory: ./web/packages/react
        run: yarn run test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        working-directory: ./web/packages/react
        run: yarn run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
