name: CI.TOKENS

on:
    pull_request:
        branches:
            - dev
            - master
        paths:
            - 'packages/tokens/**'

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}

        steps:
            - uses: actions/checkout@v2

            - name: Install (common)
              working-directory: ./packages/tokens
              run: yarn install

            - name: Build
              working-directory: ./packages/tokens
              run: yarn run build
