name: CI

on:
  pull_request:
    branches:
      - dev
      - master
  push:
    branches:
      - dev
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd web/packages/react
      - run: yarn install
      - run: yarn run install-peers
      - run: yarn run test
      - run: yarn run build
